export type InstrumentType = 'bass' | 'guitar' | 'ukulele' | 'piano';

export interface NoteInfo {
  id: string;
  label: string; 
  type: 'white' | 'black';
  blackOffset?: number; 
  soundFile: any;
}

export const INSTRUMENT_SOUNDS: Record<InstrumentType, NoteInfo[]> = {
  bass: [
    { id: 'bass_c3', label: 'C3', type: 'white', soundFile: require('../assets/sounds/bass_c3.m4a') },
    { id: 'bass_db3', label: 'Db3', type: 'black', blackOffset: 1, soundFile: require('../assets/sounds/bass_db3.m4a') },
    { id: 'bass_d3', label: 'D3', type: 'white', soundFile: require('../assets/sounds/bass_d3.m4a') },
    { id: 'bass_eb3', label: 'Eb3', type: 'black', blackOffset: 2, soundFile: require('../assets/sounds/bass_eb3.m4a') },
    { id: 'bass_e3', label: 'E3', type: 'white', soundFile: require('../assets/sounds/bass_e3.m4a') },
    { id: 'bass_f3', label: 'F3', type: 'white', soundFile: require('../assets/sounds/bass_f3.m4a') },
    { id: 'bass_gb3', label: 'Gb3', type: 'black', blackOffset: 4, soundFile: require('../assets/sounds/bass_gb3.m4a') },
    { id: 'bass_g3', label: 'G3', type: 'white', soundFile: require('../assets/sounds/bass_g3.m4a') },
    { id: 'bass_ab3', label: 'Ab3', type: 'black', blackOffset: 5, soundFile: require('../assets/sounds/bass_ab3.m4a') },
    { id: 'bass_a3', label: 'A3', type: 'white', soundFile: require('../assets/sounds/bass_a3.m4a') },
    { id: 'bass_bb3', label: 'Bb3', type: 'black', blackOffset: 6, soundFile: require('../assets/sounds/bass_bb3.m4a') },
    { id: 'bass_b3', label: 'B3', type: 'white', soundFile: require('../assets/sounds/bass_b3.m4a') },
    { id: 'bass_c4', label: 'C4', type: 'white', soundFile: require('../assets/sounds/bass_c4.m4a') },
    { id: 'bass_db4', label: 'Db4', type: 'black', blackOffset: 8, soundFile: require('../assets/sounds/bass_db4.m4a') },
    { id: 'bass_d4', label: 'D4', type: 'white', soundFile: require('../assets/sounds/bass_d4.m4a') },
    { id: 'bass_eb4', label: 'Eb4', type: 'black', blackOffset: 9, soundFile: require('../assets/sounds/bass_eb4.m4a') },
    { id: 'bass_e4', label: 'E4', type: 'white', soundFile: require('../assets/sounds/bass_e4.m4a') },
    { id: 'bass_f4', label: 'F4', type: 'white', soundFile: require('../assets/sounds/bass_f4.m4a') },
    { id: 'bass_gb4', label: 'Gb4', type: 'black', blackOffset: 11, soundFile: require('../assets/sounds/bass_gb4.m4a') },
    { id: 'bass_g4', label: 'G4', type: 'white', soundFile: require('../assets/sounds/bass_g4.m4a') },
    { id: 'bass_ab4', label: 'Ab4', type: 'black', blackOffset: 12, soundFile: require('../assets/sounds/bass_ab4.m4a') },
    { id: 'bass_a4', label: 'A4', type: 'white', soundFile: require('../assets/sounds/bass_a4.m4a') },
    { id: 'bass_bb4', label: 'Bb4', type: 'black', blackOffset: 13, soundFile: require('../assets/sounds/bass_bb4.m4a') },
    { id: 'bass_b4', label: 'B4', type: 'white', soundFile: require('../assets/sounds/bass_b4.m4a') },
    { id: 'bass_c5', label: 'C5', type: 'white', soundFile: require('../assets/sounds/bass_c5.m4a') },
  ],
  guitar: [
    { id: 'guitar_c3', label: 'C3', type: 'white', soundFile: require('../assets/sounds/guitar_c3.m4a') },
    { id: 'guitar_db3', label: 'Db3', type: 'black', blackOffset: 1, soundFile: require('../assets/sounds/guitar_db3.m4a') },
    { id: 'guitar_d3', label: 'D3', type: 'white', soundFile: require('../assets/sounds/guitar_d3.m4a') },
    { id: 'guitar_eb3', label: 'Eb3', type: 'black', blackOffset: 2, soundFile: require('../assets/sounds/guitar_eb3.m4a') },
    { id: 'guitar_e3', label: 'E3', type: 'white', soundFile: require('../assets/sounds/guitar_e3.m4a') },
    { id: 'guitar_f3', label: 'F3', type: 'white', soundFile: require('../assets/sounds/guitar_f3.m4a') },
    { id: 'guitar_gb3', label: 'Gb3', type: 'black', blackOffset: 4, soundFile: require('../assets/sounds/guitar_gb3.m4a') },
    { id: 'guitar_g3', label: 'G3', type: 'white', soundFile: require('../assets/sounds/guitar_g3.m4a') },
    { id: 'guitar_ab3', label: 'Ab3', type: 'black', blackOffset: 5, soundFile: require('../assets/sounds/guitar_ab3.m4a') },
    { id: 'guitar_a3', label: 'A3', type: 'white', soundFile: require('../assets/sounds/guitar_a3.m4a') },
    { id: 'guitar_bb3', label: 'Bb3', type: 'black', blackOffset: 6, soundFile: require('../assets/sounds/guitar_bb3.m4a') },
    { id: 'guitar_b3', label: 'B3', type: 'white', soundFile: require('../assets/sounds/guitar_b3.m4a') },
    { id: 'guitar_c4', label: 'C4', type: 'white', soundFile: require('../assets/sounds/guitar_c4.m4a') },
    { id: 'guitar_db4', label: 'Db4', type: 'black', blackOffset: 8, soundFile: require('../assets/sounds/guitar_db4.m4a') },
    { id: 'guitar_d4', label: 'D4', type: 'white', soundFile: require('../assets/sounds/guitar_d4.m4a') },
    { id: 'guitar_eb4', label: 'Eb4', type: 'black', blackOffset: 9, soundFile: require('../assets/sounds/guitar_eb4.m4a') },
    { id: 'guitar_e4', label: 'E4', type: 'white', soundFile: require('../assets/sounds/guitar_e4.m4a') },
    { id: 'guitar_f4', label: 'F4', type: 'white', soundFile: require('../assets/sounds/guitar_f4.m4a') },
    { id: 'guitar_gb4', label: 'Gb4', type: 'black', blackOffset: 11, soundFile: require('../assets/sounds/guitar_gb4.m4a') },
    { id: 'guitar_g4', label: 'G4', type: 'white', soundFile: require('../assets/sounds/guitar_g4.m4a') },
    { id: 'guitar_ab4', label: 'Ab4', type: 'black', blackOffset: 12, soundFile: require('../assets/sounds/guitar_ab4.m4a') },
    { id: 'guitar_a4', label: 'A4', type: 'white', soundFile: require('../assets/sounds/guitar_a4.m4a') },
    { id: 'guitar_bb4', label: 'Bb4', type: 'black', blackOffset: 13, soundFile: require('../assets/sounds/guitar_bb4.m4a') },
    { id: 'guitar_b4', label: 'B4', type: 'white', soundFile: require('../assets/sounds/guitar_b4.m4a') },
    { id: 'guitar_c5', label: 'C5', type: 'white', soundFile: require('../assets/sounds/guitar_c5.m4a') },
  ],
  ukulele: [
    { id: 'ukulele_c3', label: 'C3', type: 'white', soundFile: require('../assets/sounds/ukulele_c3.m4a') },
    { id: 'ukulele_db3', label: 'Db3', type: 'black', blackOffset: 1, soundFile: require('../assets/sounds/ukulele_db3.m4a') },
    { id: 'ukulele_d3', label: 'D3', type: 'white', soundFile: require('../assets/sounds/ukulele_d3.m4a') },
    { id: 'ukulele_eb3', label: 'Eb3', type: 'black', blackOffset: 2, soundFile: require('../assets/sounds/ukulele_eb3.m4a') },
    { id: 'ukulele_e3', label: 'E3', type: 'white', soundFile: require('../assets/sounds/ukulele_e3.m4a') },
    { id: 'ukulele_f3', label: 'F3', type: 'white', soundFile: require('../assets/sounds/ukulele_f3.m4a') },
    { id: 'ukulele_gb3', label: 'Gb3', type: 'black', blackOffset: 4, soundFile: require('../assets/sounds/ukulele_gb3.m4a') },
    { id: 'ukulele_g3', label: 'G3', type: 'white', soundFile: require('../assets/sounds/ukulele_g3.m4a') },
    { id: 'ukulele_ab3', label: 'Ab3', type: 'black', blackOffset: 5, soundFile: require('../assets/sounds/ukulele_ab3.m4a') },
    { id: 'ukulele_a3', label: 'A3', type: 'white', soundFile: require('../assets/sounds/ukulele_a3.m4a') },
    { id: 'ukulele_bb3', label: 'Bb3', type: 'black', blackOffset: 6, soundFile: require('../assets/sounds/ukulele_bb3.m4a') },
    { id: 'ukulele_b3', label: 'B3', type: 'white', soundFile: require('../assets/sounds/ukulele_b3.m4a') },
    { id: 'ukulele_c4', label: 'C4', type: 'white', soundFile: require('../assets/sounds/ukulele_c4.m4a') },
    { id: 'ukulele_db4', label: 'Db4', type: 'black', blackOffset: 8, soundFile: require('../assets/sounds/ukulele_db4.m4a') },
    { id: 'ukulele_d4', label: 'D4', type: 'white', soundFile: require('../assets/sounds/ukulele_d4.m4a') },
    { id: 'ukulele_eb4', label: 'Eb4', type: 'black', blackOffset: 9, soundFile: require('../assets/sounds/ukulele_eb4.m4a') },
    { id: 'ukulele_e4', label: 'E4', type: 'white', soundFile: require('../assets/sounds/ukulele_e4.m4a') },
    { id: 'ukulele_f4', label: 'F4', type: 'white', soundFile: require('../assets/sounds/ukulele_f4.m4a') },
    { id: 'ukulele_gb4', label: 'Gb4', type: 'black', blackOffset: 11, soundFile: require('../assets/sounds/ukulele_gb4.m4a') },
    { id: 'ukulele_g4', label: 'G4', type: 'white', soundFile: require('../assets/sounds/ukulele_g4.m4a') },
    { id: 'ukulele_ab4', label: 'Ab4', type: 'black', blackOffset: 12, soundFile: require('../assets/sounds/ukulele_ab4.m4a') },
    { id: 'ukulele_a4', label: 'A4', type: 'white', soundFile: require('../assets/sounds/ukulele_a4.m4a') },
    { id: 'ukulele_bb4', label: 'Bb4', type: 'black', blackOffset: 13, soundFile: require('../assets/sounds/ukulele_bb4.m4a') },
    { id: 'ukulele_b4', label: 'B4', type: 'white', soundFile: require('../assets/sounds/ukulele_b4.m4a') },
    { id: 'ukulele_c5', label: 'C5', type: 'white', soundFile: require('../assets/sounds/ukulele_c5.m4a') },
  ],
  piano: [
    { id: 'piano_c3', label: 'C3', type: 'white', soundFile: require('../assets/sounds/piano_c3.m4a') },
    { id: 'piano_db3', label: 'Db3', type: 'black', blackOffset: 1, soundFile: require('../assets/sounds/piano_db3.m4a') },
    { id: 'piano_d3', label: 'D3', type: 'white', soundFile: require('../assets/sounds/piano_d3.m4a') },
    { id: 'piano_eb3', label: 'Eb3', type: 'black', blackOffset: 2, soundFile: require('../assets/sounds/piano_eb3.m4a') },
    { id: 'piano_e3', label: 'E3', type: 'white', soundFile: require('../assets/sounds/piano_e3.m4a') },
    { id: 'piano_f3', label: 'F3', type: 'white', soundFile: require('../assets/sounds/piano_f3.m4a') },
    { id: 'piano_gb3', label: 'Gb3', type: 'black', blackOffset: 4, soundFile: require('../assets/sounds/piano_gb3.m4a') },
    { id: 'piano_g3', label: 'G3', type: 'white', soundFile: require('../assets/sounds/piano_g3.m4a') },
    { id: 'piano_ab3', label: 'Ab3', type: 'black', blackOffset: 5, soundFile: require('../assets/sounds/piano_ab3.m4a') },
    { id: 'piano_a3', label: 'A3', type: 'white', soundFile: require('../assets/sounds/piano_a3.m4a') },
    { id: 'piano_bb3', label: 'Bb3', type: 'black', blackOffset: 6, soundFile: require('../assets/sounds/piano_bb3.m4a') },
    { id: 'piano_b3', label: 'B3', type: 'white', soundFile: require('../assets/sounds/piano_b3.m4a') },
    { id: 'piano_c4', label: 'C4', type: 'white', soundFile: require('../assets/sounds/piano_c4.m4a') },
    { id: 'piano_db4', label: 'Db4', type: 'black', blackOffset: 8, soundFile: require('../assets/sounds/piano_db4.m4a') },
    { id: 'piano_d4', label: 'D4', type: 'white', soundFile: require('../assets/sounds/piano_d4.m4a') },
    { id: 'piano_eb4', label: 'Eb4', type: 'black', blackOffset: 9, soundFile: require('../assets/sounds/piano_eb4.m4a') },
    { id: 'piano_e4', label: 'E4', type: 'white', soundFile: require('../assets/sounds/piano_e4.m4a') },
    { id: 'piano_f4', label: 'F4', type: 'white', soundFile: require('../assets/sounds/piano_f4.m4a') },
    { id: 'piano_gb4', label: 'Gb4', type: 'black', blackOffset: 11, soundFile: require('../assets/sounds/piano_gb4.m4a') },
    { id: 'piano_g4', label: 'G4', type: 'white', soundFile: require('../assets/sounds/piano_g4.m4a') },
    { id: 'piano_ab4', label: 'Ab4', type: 'black', blackOffset: 12, soundFile: require('../assets/sounds/piano_ab4.m4a') },
    { id: 'piano_a4', label: 'A4', type: 'white', soundFile: require('../assets/sounds/piano_a4.m4a') },
    { id: 'piano_bb4', label: 'Bb4', type: 'black', blackOffset: 13, soundFile: require('../assets/sounds/piano_bb4.m4a') },
    { id: 'piano_b4', label: 'B4', type: 'white', soundFile: require('../assets/sounds/piano_b4.m4a') },
    { id: 'piano_c5', label: 'C5', type: 'white', soundFile: require('../assets/sounds/piano_c5.m4a') },
  ],
};
